HDDS-1384

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: Test Flaky
+name: Reproduce Flaky Tests
 
 on: [push, pull_request]
 
@@ -8,25 +8,29 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
-      - name: Set up JDK 11
+      - name: Set up JDK 8
         uses: actions/setup-java@v2
         with:
           distribution: 'adopt'
-          java-version: '11'
-      - name: Checkout version
-        run: git checkout cc2babc1f75c93bf89a8f10da525f944c15d02ea
-
-      - name: Compile the project
-        run: mvn test-compile -pl hadoop-tools/hadoop-distcp -am -Drat.skip
-  
-      - name: Run tests
-        run: mvn -pl hadoop-tools/hadoop-distcp test -Dtest=org.apache.hadoop.tools.util.TestThrottledInputStream#testRead
+          java-version: '8'
+          
+      # - name: maven clean install 
+      #   run: mvn clean install -Dcheckstyle.skip -Drat.skip -U
         
-      # - name: Set up JDK 8 for NonDex
-      #   uses: actions/setup-java@v2
-      #   with:
-      #     distribution: 'adopt'
-      #     java-version: '8'
+      # - name: Compile Module
+      #   run: mvn test-compile -am -Dcheckstyle.skip -Drat.skip -U
+      - name: Check
+        uses: actions/checkout@v3
+        with:
+          ref: 0af4011580878566213016af0c32633eabd15100
   
-      - name: Run NonDex to check for flaky tests
-        run: mvn -pl hadoop-tools/hadoop-distcp edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=org.apache.hadoop.tools.util.TestThrottledInputStream#testRead -DnondexRuns=20
+      - name: Test with Maven 
+        run: | 
+              for i in {1..5}; do mvn test -Dtest=org.apache.hadoop.ozone.client.rpc.TestBlockOutputStreamWithFailures -DfailIfNoTests=false -Drat.skip -fae; done#>>test_log_DOXIATOOLS-64.txt || echo "Test iteration $i failed">>test_log_DOXIATOOLS-64.txt; done
+              
+      # - name: Upload Test Log 
+      #   if: always() 
+      #   uses: actions/upload-artifact@v2 
+      #   with: 
+      #     name: test_log_DOXIATOOLS-64
+      #     path: test_log_DOXIATOOLS-64.txt
