HDDS-1341

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,15 +22,15 @@ jobs:
       - name: Check
         uses: actions/checkout@v3
         with:
-          ref: 0af4011580878566213016af0c32633eabd15100
+          ref: d78854b928bb877f26b11b5b212a100a79941f35
 
-      - name: Replace Snapshot
-        run: |
-              find . -type f -exec sed -i 's/3.3.0-SNAPSHOT/3.3.0/g' {} +
+      # - name: Replace Snapshot
+      #   run: |
+      #         find . -type f -exec sed -i 's/3.3.0-SNAPSHOT/3.3.0/g' {} +
   
       - name: Test with Maven 
         run: | 
-              for i in {1..5}; do mvn test -Dtest=org.apache.hadoop.ozone.client.rpc.TestBlockOutputStreamWithFailures -DfailIfNoTests=false -Drat.skip -fae; done#>>test_log_DOXIATOOLS-64.txt || echo "Test iteration $i failed">>test_log_DOXIATOOLS-64.txt; done
+              for i in {1..5}; do mvn test -Dtest=org.apache.hadoop.ozone.container.TestContainerReplication#testContainerReplication -DfailIfNoTests=false -Drat.skip -fae; done#>>test_log_DOXIATOOLS-64.txt || echo "Test iteration $i failed">>test_log_DOXIATOOLS-64.txt; done
               
       # - name: Upload Test Log 
       #   if: always() 
